---
swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: 'virtual-store-project-back-end.herokuapp.com'
basePath: "/"
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: product-controller
  description: Product Controller
- name: user-controller
  description: User Controller
paths:
  "/error":
    get:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingGET
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    head:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingHEAD
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
    post:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingPUT
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingDELETE
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
    options:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingOPTIONS
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
    patch:
      tags:
      - basic-error-controller
      summary: error
      operationId: errorUsingPATCH
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  "/v1/product":
    post:
      tags:
      - product-controller
      summary: createProduct
      operationId: createProductUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: createProductRequestParameter
        description: createProductRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/CreateProductRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
      - product-controller
      summary: deleteProduct
      operationId: deleteProductUsingDELETE
      produces:
      - "*/*"
      parameters:
      - in: body
        name: deleteProductRequest
        description: deleteProductRequest
        required: true
        schema:
          "$ref": "#/definitions/DeleteProductRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  "/v1/product/buy":
    post:
      tags:
      - product-controller
      summary: buyProduct
      operationId: buyProductUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: buyProductRequestParameter
        description: buyProductRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/BuyProductRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  "/v1/product/update":
    put:
      tags:
      - product-controller
      summary: updateProduct
      operationId: updateProductUsingPUT
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: updateProductRequestParameter
        description: updateProductRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/UpdateProductRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  "/v1/user":
    get:
      tags:
      - user-controller
      summary: getUserDetails
      operationId: getUserDetailsUsingGET
      produces:
      - "*/*"
      parameters:
      - in: body
        name: getUserRequestParameter
        description: getUserRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/GetUserDetailRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
      - user-controller
      summary: createUser
      operationId: createUserUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: createUserRequestParameter
        description: createUserRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/CreateUserRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
      - user-controller
      summary: updateUserDetails
      operationId: updateUserDetailsUsingPUT
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: updateUserRequestParameter
        description: updateUserRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/UpdateUserRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
      - user-controller
      summary: deleteUserDetails
      operationId: deleteUserDetailsUsingDELETE
      produces:
      - "*/*"
      parameters:
      - in: body
        name: deleteUserRequestParameter
        description: deleteUserRequestParameter
        required: true
        schema:
          "$ref": "#/definitions/DeleteUserRequest"
      responses:
        '200':
          description: OK
          schema:
            type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  Address:
    type: object
    properties:
      birthDate:
        type: string
        format: date-time
      documentNumber:
        type: string
      email:
        type: string
      houseNumber:
        type: string
      id:
        type: string
      name:
        type: string
      streetName:
        type: string
      userAdresses:
        type: array
        items:
          "$ref": "#/definitions/Address"
      zipCode:
        type: string
    title: Address
  BuyProductRequest:
    type: object
    properties:
      idProduct:
        type: string
    title: BuyProductRequest
  CreateProductRequest:
    type: object
    properties:
      createdProductDate:
        type: string
        format: date-time
      productDescription:
        type: string
      productName:
        type: string
      productValue:
        type: number
      statusProduct:
        type: string
        enum:
        - SOLD
        - NOT_SOLD
    title: CreateProductRequest
  CreateUserRequest:
    type: object
    properties:
      birthDate:
        type: string
        example: dd-MM-yyyy
      documentNumber:
        type: string
      email:
        type: string
      name:
        type: string
      userAdresses:
        type: array
        items:
          "$ref": "#/definitions/Address"
    title: CreateUserRequest
  DeleteProductRequest:
    type: object
    properties:
      productId:
        type: string
    title: DeleteProductRequest
  DeleteUserRequest:
    type: object
    properties:
      id:
        type: string
    title: DeleteUserRequest
  GetUserDetailRequest:
    type: object
    properties:
      id:
        type: string
    title: GetUserDetailRequest
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
        - 100 CONTINUE
        - 101 SWITCHING_PROTOCOLS
        - 102 PROCESSING
        - 103 CHECKPOINT
        - 200 OK
        - 201 CREATED
        - 202 ACCEPTED
        - 203 NON_AUTHORITATIVE_INFORMATION
        - 204 NO_CONTENT
        - 205 RESET_CONTENT
        - 206 PARTIAL_CONTENT
        - 207 MULTI_STATUS
        - 208 ALREADY_REPORTED
        - 226 IM_USED
        - 300 MULTIPLE_CHOICES
        - 301 MOVED_PERMANENTLY
        - 302 FOUND
        - 302 MOVED_TEMPORARILY
        - 303 SEE_OTHER
        - 304 NOT_MODIFIED
        - 305 USE_PROXY
        - 307 TEMPORARY_REDIRECT
        - 308 PERMANENT_REDIRECT
        - 400 BAD_REQUEST
        - 401 UNAUTHORIZED
        - 402 PAYMENT_REQUIRED
        - 403 FORBIDDEN
        - 404 NOT_FOUND
        - 405 METHOD_NOT_ALLOWED
        - 406 NOT_ACCEPTABLE
        - 407 PROXY_AUTHENTICATION_REQUIRED
        - 408 REQUEST_TIMEOUT
        - 409 CONFLICT
        - 410 GONE
        - 411 LENGTH_REQUIRED
        - 412 PRECONDITION_FAILED
        - 413 PAYLOAD_TOO_LARGE
        - 413 REQUEST_ENTITY_TOO_LARGE
        - 414 URI_TOO_LONG
        - 414 REQUEST_URI_TOO_LONG
        - 415 UNSUPPORTED_MEDIA_TYPE
        - 416 REQUESTED_RANGE_NOT_SATISFIABLE
        - 417 EXPECTATION_FAILED
        - 418 I_AM_A_TEAPOT
        - 419 INSUFFICIENT_SPACE_ON_RESOURCE
        - 420 METHOD_FAILURE
        - 421 DESTINATION_LOCKED
        - 422 UNPROCESSABLE_ENTITY
        - 423 LOCKED
        - 424 FAILED_DEPENDENCY
        - 425 TOO_EARLY
        - 426 UPGRADE_REQUIRED
        - 428 PRECONDITION_REQUIRED
        - 429 TOO_MANY_REQUESTS
        - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
        - 451 UNAVAILABLE_FOR_LEGAL_REASONS
        - 500 INTERNAL_SERVER_ERROR
        - 501 NOT_IMPLEMENTED
        - 502 BAD_GATEWAY
        - 503 SERVICE_UNAVAILABLE
        - 504 GATEWAY_TIMEOUT
        - 505 HTTP_VERSION_NOT_SUPPORTED
        - 506 VARIANT_ALSO_NEGOTIATES
        - 507 INSUFFICIENT_STORAGE
        - 508 LOOP_DETECTED
        - 509 BANDWIDTH_LIMIT_EXCEEDED
        - 510 NOT_EXTENDED
        - 511 NETWORK_AUTHENTICATION_REQUIRED
      view:
        "$ref": "#/definitions/View"
      viewName:
        type: string
    title: ModelAndView
  UpdateProductRequest:
    type: object
    properties:
      idProduct:
        type: string
      productDescription:
        type: string
      productName:
        type: string
      productValue:
        type: number
    title: UpdateProductRequest
  UpdateUserRequest:
    type: object
    properties:
      birthDate:
        type: string
        example: dd-MM-yyyy
      id:
        type: string
      name:
        type: string
    title: UpdateUserRequest
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View
